### ISSUE TITLE
Error in loss

### ISSUE THREAD

**Issue by suvojit-0x55aa** [adamian98/pulse#16]
I'm running on a single image and getting the following error.

```
Traceback (most recent call last):
  File "run.py", line 79, in <module>
    for j,(HR,LR) in enumerate(model(ref_im,**kwargs)):
  File "/home/ubuntu/pulse/PULSE.py", line 149, in forward
    loss, loss_dict = loss_builder(latent_in, gen_im)
  File "/home/ubuntu/miniconda3/envs/pulse/lib/python3.8/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/pulse/loss.py", line 54, in forward
    tmp_loss = loss_fun_dict[loss_type](**var_dict)
  File "/home/ubuntu/pulse/loss.py", line 23, in _loss_l2
    return ((gen_im_lr - ref_im).pow(2).mean((1, 2, 3)).clamp(min=self.eps).sum())
RuntimeError: The size of tensor a (3) must match the size of tensor b (4) at non-singleton dimension 1
```

I printed the variables `gen_im_lr` & `ref_im` and got the following:
```
torch.Size([1, 3, 32, 32]) torch.Size([1, 4, 32, 32])
```

**Comment by Coolbeer** [comment]
I had the same issue, I fixed it by removing the alpha channel of the image.

**Comment by suvojit-0x55aa** [comment]
Thanks @Coolbeer  that fixed it
