### ISSUE TITLE
'no attribute ndim'

### ISSUE THREAD

**Issue by g30ba1** [adamian98/pulse#21]
I was able to download the three files required by align_face.py and PULSE.py, then I was able to downsample 3 images with no problem, but when I try to run "run.py", I get an error:

Loading Synthesis Network
Downloading https://drive.google.com/uc?id=1xKDEzjfGPa1s1iDYucH4eSxLvl1MuLE1 ... done
Traceback (most recent call last):
  File "run.py", line 79, in <module>
    for j,(HR,LR) in enumerate(model(ref_im,**kwargs)):
  File "/home/pyimagesearch/Downloads/pulse-master/PULSE.py", line 114, in forward
    opt = SphericalOptimizer(opt_func, var_list, lr=learning_rate)
  File "/home/pyimagesearch/Downloads/pulse-master/SphericalOptimizer.py", line 17, in __init__
    self.radii = {param: (param.pow(2).sum(tuple(range(2,param.ndim)),keepdim=True)+1e-9).sqrt() for param in params}
  File "/home/pyimagesearch/Downloads/pulse-master/SphericalOptimizer.py", line 17, in <dictcomp>
    self.radii = {param: (param.pow(2).sum(tuple(range(2,param.ndim)),keepdim=True)+1e-9).sqrt() for param in params}
AttributeError: 'Tensor' object has no attribute 'ndim'

--------------------------------------------------------------------------------------------------------------
I´m using a Jetson Nano, with CUDA and all the modules and dependences required by the program.

Some tip?

**Comment by bmdisbrow** [comment]
Try uninstalling and re-installing pytorch again.

**Comment by bmdisbrow** [comment]
conda uninstall pytorch
pip uninstall torch
pip uninstall torch # run this command twice
conda install pytorch torchvision cudatoolkit=10.2 -c pytorch

**Comment by rockjicks** [comment]
I met this problem too. Have you solved it

**Comment by rockjicks** [comment]
I Replace  param.ndim  to  len(list(param.size())   in SphericalOptimizer.py
it worked well
