### ISSUE TITLE
_pickle.UnpicklingError: invalid load key, '\x01'.

### ISSUE THREAD

**Issue by heiheiheibj** [adamian98/pulse#25]
Loading Synthesis Network
Traceback (most recent call last):
  File "run.py", line 58, in <module>
    model = PULSE(cache_dir=kwargs["cache_dir"])
  File "D:\pulse\pulse\PULSE.py", line 24, in __init__
    self.synthesis.load_state_dict(torch.load(f))
  File "D:\ProgramData\Anaconda3\lib\site-packages\torch\serialization.py", line 593, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "D:\ProgramData\Anaconda3\lib\site-packages\torch\serialization.py", line 763, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '\x01'.

What should I do about it?
thx ..

**Comment by Ekkoruse** [comment]
there are three different link of file.
