### ISSUE TITLE
problem creating  a Conda environment from the provided YAML

### ISSUE THREAD

**Issue by fkiaee** [adamian98/pulse#30]
conda env create -f environment.yml
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/usr/local/lib/python3.7/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/usr/local/lib/python3.7/site-packages/conda_env/cli/main.py", line 80, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/usr/local/lib/python3.7/site-packages/conda_env/cli/main_create.py", line 80, in execute
        directory=os.getcwd())
      File "/usr/local/lib/python3.7/site-packages/conda_env/specs/__init__.py", line 40, in detect
        if spec.can_handle():
      File "/usr/local/lib/python3.7/site-packages/conda_env/specs/yaml_file.py", line 18, in can_handle
        self._environment = env.from_file(self.filename)
      File "/usr/local/lib/python3.7/site-packages/conda_env/env.py", line 151, in from_file
        return from_yaml(yamlstr, filename=filename)
      File "/usr/local/lib/python3.7/site-packages/conda_env/env.py", line 136, in from_yaml
        data = yaml_load_standard(yamlstr)
      File "/usr/local/lib/python3.7/site-packages/conda/common/serialize.py", line 76, in yaml_load_standard
        return yaml.load(string, Loader=yaml.Loader, version="1.2")
      File "/usr/local/lib/python3.7/site-packages/ruamel_yaml/main.py", line 935, in load
        return loader._constructor.get_single_data()
      File "/usr/local/lib/python3.7/site-packages/ruamel_yaml/constructor.py", line 109, in get_single_data
        node = self.composer.get_single_node()
      File "/usr/local/lib/python3.7/site-packages/ruamel_yaml/composer.py", line 78, in get_single_node
        document = self.compose_document()
      File "/usr/local/lib/python3.7/site-packages/ruamel_yaml/composer.py", line 104, in compose_document
        self.parser.get_event()
      File "/usr/local/lib/python3.7/site-packages/ruamel_yaml/parser.py", line 163, in get_event
        self.current_event = self.state()
      File "/usr/local/lib/python3.7/site-packages/ruamel_yaml/parser.py", line 239, in parse_document_end
        token = self.scanner.peek_token()
      File "/usr/local/lib/python3.7/site-packages/ruamel_yaml/scanner.py", line 182, in peek_token
        self.fetch_more_tokens()
      File "/usr/local/lib/python3.7/site-packages/ruamel_yaml/scanner.py", line 282, in fetch_more_tokens
        return self.fetch_value()
      File "/usr/local/lib/python3.7/site-packages/ruamel_yaml/scanner.py", line 655, in fetch_value
        self.reader.get_mark(),
    ruamel_yaml.scanner.ScannerError: mapping values are not allowed here
      in "<unicode string>", line 32, column 44:
         ... ame="description" content="PULSE: Self-Supervised Photo Upsampli ... 
                                             ^ (line: 32)

`$ /usr/local/bin/conda-env create -f environment.yml`

  environment variables:
                 CIO_TEST=<not set>
  CONDA_AUTO_UPDATE_CONDA=false
               CONDA_ROOT=/usr/local
          LD_LIBRARY_PATH=/usr/local/nvidia/lib:/usr/local/nvidia/lib64
             LIBRARY_PATH=/usr/local/cuda/lib64/stubs
                     PATH=/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/b
                          in:/usr/sbin:/usr/bin:/sbin:/bin:/tools/node/bin:/tools/google-cloud-
                          sdk/bin:/opt/bin
               PYTHONPATH=/env/python
           PYTHONWARNINGS=ignore:::pip._internal.cli.base_command
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
       user config file : /root/.condarc
 populated config files : /root/.condarc
          conda version : 4.8.2
    conda-build version : not installed
         python version : 3.7.6.final.0
       virtual packages : __glibc=2.27
       base environment : /usr/local  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /usr/local/pkgs
                          /root/.conda/pkgs
       envs directories : /usr/local/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.2 requests/2.22.0 CPython/3.7.6 Linux/4.19.104+ ubuntu/18.04.3 glibc/2.27
                UID:GID : 0:0
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.

**Comment by leihuayi** [comment]
It does not solve your problem in an easy way, but you could install it in a Docker to run your code, in case the problem comes from your Conda installation ?

1. Edit pulse.yml : add conda-forge channel, and remove all elements after the second "=" in dependancies (as stated in the README). Change `libfortran=3.0.1` to `libfortran` as this version only works on osx.
2. Write a Dockerfile in pulse folder:
```
# Use a docker image as base image
FROM nvidia/cuda:9.0-cudnn7-runtime
# Declare some ARGuments
ARG PYTHON_VERSION=3.6
ARG CONDA_VERSION=3
ARG CONDA_PY_VERSION=4.5.11
ARG NAME=pulse
# Installation of some libraries / RUN some commands on the base image
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y — no-install-recommends python3-pip python3-dev \
    bzip2 libopenblas-dev pbzip2 libgl1-mesa-glx && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
# INSTALLATION OF CONDA
ENV PATH /opt/conda/bin:$PATH
RUN curl 'https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh' > ~/miniconda.sh && \
    /bin/bash ~/miniconda.sh -b -p /opt/conda && \
    rm ~/miniconda.sh && \
    /opt/conda/bin/conda clean -tipsy && \
    ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh && \
    echo “. /opt/conda/etc/profile.d/conda.sh” >> ~/.bashrc && \
    echo “conda activate base” >> ~/.bashrc
ENV PATH /opt/conda/envs/gpuenvs/bin:$PATH

WORKDIR /home/${NAME}

# Install the python dependencies
COPY . .
RUN conda update -n base -c defaults conda
RUN conda env create -f pulse.yml

CMD /bin/bash

```
2. Build `docker build –t pulse:latest .`
3. Run `docker run -it --rm --gpus all --name pulse --entrypoint bash -v "$PWD:/home/pulse" pulse:latest` (you might need to change --gpus all by --runtime==nvidia if your Docker version is older
4. Once you are inside the container, your "pulse" folder on your computer is in sync with the "pulse" folder on the docker. You can quit the container, add images, come back in again. Activate the environment by running `conda activate pulse` then run the code like usual `python run.py` .
