### ISSUE TITLE
Google Drive quota exceeded when running align_face

### ISSUE THREAD

**Issue by leihuayi** [adamian98/pulse#33]
Cannot run align_face.
```
(pulse) root@e2bbc3333453:/home/pulse# python align_face.py
Downloading Shape Predictor
Downloading https://drive.google.com/uc?id=1huhv8PYpNNKbGCLOaYUjOgR1pY5pmbJx ............ failed
Traceback (most recent call last):
  File "align_face.py", line 34, in <module>
    f=open_url("https://drive.google.com/uc?id=1huhv8PYpNNKbGCLOaYUjOgR1pY5pmbJx", cache_dir=cache_dir, return_path=True)
  File "/home/pulse/drive.py", line 66, in open_url
    raise IOError("Google Drive quota exceeded")
OSError: Google Drive quota exceeded
```

Probably sharing a new link would fix this.

About another matter, maybe it would be best to warn people to put their input images as png. It took me a while to understand why my images weren't processed when runnin "python run.py'.

**Comment by leihuayi** [comment]
Sorry didn't see it was mentionned on the readme. closing
