### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by jameswangcnbj** [adamian98/pulse#44]
Loading Synthesis Network
Traceback (most recent call last):
  File "./run.py", line 79, in <module>
    for j,(HR,LR) in enumerate(model(ref_im,**kwargs)):
  File "/usr/local/src/pulse/PULSE.py", line 126, in forward
    loss_builder = LossBuilder(ref_im, loss_str, eps).cuda()
  File "/usr/local/src/pulse/loss.py", line 7, in __init__
    assert ref_im.shape[2]==ref_im.shape[3]
AssertionError

**Comment by KamalChhirang** [comment]
I think the width & height needs to be the same and probably exactly 1024x1024.

**Comment by ss24cs** [comment]
I got same error, my input images size problem? Thx.
