### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by xdTAGCLAN** [adamian98/pulse#47]
When i do "conda env create -n pulse -f pulse.yml"
i get this very long error: Ran pip subprocess with arguments:
['D:\\Program Files\\Anaconda\\envs\\pulse\\python.exe', '-m', 'pip', 'install', '-U', '-r', 'C:\\Users\\gijse\\Downloads\\PULSE\\pulse-master\\condaenv.93ram30n.requirements.txt']
Pip subprocess output:
Collecting dlib==19.19.0
  Downloading dlib-19.19.0.tar.gz (3.2 MB)
Building wheels for collected packages: dlib
  Building wheel for dlib (setup.py): started
  Building wheel for dlib (setup.py): finished with status 'error'
  Running setup.py clean for dlib
Failed to build dlib
Installing collected packages: dlib
    Running setup.py install for dlib: started
    Running setup.py install for dlib: finished with status 'error'

Pip subprocess error:
  ERROR: Command errored out with exit status 1:
   command: 'D:\Program Files\Anaconda\envs\pulse\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\gijse\\AppData\\Local\\Temp\\pip-install-bh9nnp7l\\dlib\\setup.py'"'"'; __file__='"'"'C:\\Users\\gijse\\AppData\\Local\\Temp\\pip-install-bh9nnp7l\\dlib\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\gijse\AppData\Local\Temp\pip-wheel-i0g75ms_'
       cwd: C:\Users\gijse\AppData\Local\Temp\pip-install-bh9nnp7l\dlib\
  Complete output (53 lines):
  running bdist_wheel
  running build
  running build_py
  package init file 'dlib\__init__.py' not found (or not a regular file)
  running build_ext
  Traceback (most recent call last):
    File "C:\Users\gijse\AppData\Local\Temp\pip-install-bh9nnp7l\dlib\setup.py", line 120, in get_cmake_version
      out = subprocess.check_output(['cmake', '--version'])
    File "D:\Program Files\Anaconda\envs\pulse\lib\subprocess.py", line 411, in check_output
      return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
    File "D:\Program Files\Anaconda\envs\pulse\lib\subprocess.py", line 489, in run
      with Popen(*popenargs, **kwargs) as process:
    File "D:\Program Files\Anaconda\envs\pulse\lib\subprocess.py", line 854, in __init__
      self._execute_child(args, executable, preexec_fn, close_fds,
    File "D:\Program Files\Anaconda\envs\pulse\lib\subprocess.py", line 1307, in _execute_child
      hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
  FileNotFoundError: [WinError 2] The system cannot find the file specified

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\gijse\AppData\Local\Temp\pip-install-bh9nnp7l\dlib\setup.py", line 223, in <module>
      setup(
    File "D:\Program Files\Anaconda\envs\pulse\lib\site-packages\setuptools\__init__.py", line 161, in setup
      return distutils.core.setup(**attrs)
    File "D:\Program Files\Anaconda\envs\pulse\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "D:\Program Files\Anaconda\envs\pulse\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "D:\Program Files\Anaconda\envs\pulse\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "D:\Program Files\Anaconda\envs\pulse\lib\site-packages\wheel\bdist_wheel.py", line 223, in run
      self.run_command('build')
    File "D:\Program Files\Anaconda\envs\pulse\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "D:\Program Files\Anaconda\envs\pulse\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "D:\Program Files\Anaconda\envs\pulse\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "D:\Program Files\Anaconda\envs\pulse\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "D:\Program Files\Anaconda\envs\pulse\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\gijse\AppData\Local\Temp\pip-install-bh9nnp7l\dlib\setup.py", line 129, in run
      cmake_version = self.get_cmake_version()
    File "C:\Users\gijse\AppData\Local\Temp\pip-install-bh9nnp7l\dlib\setup.py", line 122, in get_cmake_version
      raise RuntimeError("\n*******************************************************************\n" +
  RuntimeError:
  *******************************************************************
   CMake must be installed to build the following extensions: dlib
  *******************************************************************

  ----------------------------------------
  ERROR: Failed building wheel for dlib
    ERROR: Command errored out with exit status 1:
     command: 'D:\Program Files\Anaconda\envs\pulse\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\gijse\\AppData\\Local\\Temp\\pip-install-bh9nnp7l\\dlib\\setup.py'"'"'; __file__='"'"'C:\\Users\\gijse\\AppData\\Local\\Temp\\pip-install-bh9nnp7l\\dlib\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\gijse\AppData\Local\Temp\pip-record-637lz1en\install-record.txt' --single-version-externally-managed --compile --install-headers 'D:\Program Files\Anaconda\envs\pulse\Include\dlib'
         cwd: C:\Users\gijse\AppData\Local\Temp\pip-install-bh9nnp7l\dlib\
    Complete output (55 lines):
    running install
    running build
    running build_py
    package init file 'dlib\__init__.py' not found (or not a regular file)
    running build_ext
    Traceback (most recent call last):
      File "C:\Users\gijse\AppData\Local\Temp\pip-install-bh9nnp7l\dlib\setup.py", line 120, in get_cmake_version
        out = subprocess.check_output(['cmake', '--version'])
      File "D:\Program Files\Anaconda\envs\pulse\lib\subprocess.py", line 411, in check_output
        return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
      File "D:\Program Files\Anaconda\envs\pulse\lib\subprocess.py", line 489, in run
        with Popen(*popenargs, **kwargs) as process:
      File "D:\Program Files\Anaconda\envs\pulse\lib\subprocess.py", line 854, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "D:\Program Files\Anaconda\envs\pulse\lib\subprocess.py", line 1307, in _execute_child
        hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
    FileNotFoundError: [WinError 2] The system cannot find the file specified

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\gijse\AppData\Local\Temp\pip-install-bh9nnp7l\dlib\setup.py", line 223, in <module>
        setup(
      File "D:\Program Files\Anaconda\envs\pulse\lib\site-packages\setuptools\__init__.py", line 161, in setup
        return distutils.core.setup(**attrs)
      File "D:\Program Files\Anaconda\envs\pulse\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "D:\Program Files\Anaconda\envs\pulse\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "D:\Program Files\Anaconda\envs\pulse\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "D:\Program Files\Anaconda\envs\pulse\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "D:\Program Files\Anaconda\envs\pulse\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "D:\Program Files\Anaconda\envs\pulse\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "D:\Program Files\Anaconda\envs\pulse\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "D:\Program Files\Anaconda\envs\pulse\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "D:\Program Files\Anaconda\envs\pulse\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "D:\Program Files\Anaconda\envs\pulse\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\gijse\AppData\Local\Temp\pip-install-bh9nnp7l\dlib\setup.py", line 129, in run
        cmake_version = self.get_cmake_version()
      File "C:\Users\gijse\AppData\Local\Temp\pip-install-bh9nnp7l\dlib\setup.py", line 122, in get_cmake_version
        raise RuntimeError("\n*******************************************************************\n" +
    RuntimeError:
    *******************************************************************
     CMake must be installed to build the following extensions: dlib
    *******************************************************************

    ----------------------------------------
ERROR: Command errored out with exit status 1: 'D:\Program Files\Anaconda\envs\pulse\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\gijse\\AppData\\Local\\Temp\\pip-install-bh9nnp7l\\dlib\\setup.py'"'"'; __file__='"'"'C:\\Users\\gijse\\AppData\\Local\\Temp\\pip-install-bh9nnp7l\\dlib\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\gijse\AppData\Local\Temp\pip-record-637lz1en\install-record.txt' --single-version-externally-managed --compile --install-headers 'D:\Program Files\Anaconda\envs\pulse\Include\dlib' Check the logs for full command output.

**Comment by voidlynx** [comment]
install CMake

**Comment by metzo007** [comment]
I get the some error with Cmake installed

C:\AI\PULSE\pulse-master>pip install cmake
Requirement already satisfied: cmake in c:\users\xxx\appdata\local\programs\python\python37-32\lib\site-packages (3.18.4.post1)
